version: "3.8"

services:
  app:
    build: .
    container_name: codeigniter_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    networks:
      - ci4-network

  nginx:
    image: nginx:latest
    container_name: codeigniter_nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - ci4-network

  db:
    image: postgres:latest
    container_name: codeigniter_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ci4db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - ci4-network

  redis:
    image: redis:latest
    container_name: codeigniter_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ci4-network

volumes:
  pg_data:
  redis_data:

networks:
  ci4-network:
    driver: bridge